version: '3'

services:
  api:
    container_name: api
    build:
      context: ./movie-api
    ports:
      - 8090:3000
    environment:
      - DATABASE_PASSWORD=1234
      - DATABASE_USER=postgres
      - DATABASE_NAME=api
      - DATABASE_HOST=database
      - DATABASE_PORT=5432

  database:
    container_name: database
    image: postgres:15.2
    ports:
      - 8080:5432
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=api
    volumes:
      - database-api:/var/lib/postgresql/data

volumes:
  database-api: